import { SheetProvider } from "@/features/accounts/components/sheet-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  ClerkProvider,
} from '@clerk/nextjs';

import QueryProvider from "@/providers/query-provider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import "./globals.css";
import { Toaster } from "sonner";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <ReactQueryDevtools initialIsOpen={false} />
            <SheetProvider/>
            <Toaster/>
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
